// English content for the companion bots. Everything here is written so the bots stay obviously bots:
// no claims of eating, sleeping, travelling or having a body.

export default {
  language: "en",

  // `answers` are neutral replies a bot can give when nobody else answers
  questions: [
    { id: "q-pineapple", text: "Pineapple on pizza: crime or genius?", answers: ["Genius. Sweet and salty is a classic for a reason.", "Crime. But I would still watch the trial.", "Genius, and I will not be taking questions."] },
    { id: "q-superpower", text: "You get one useless superpower. Which one are you picking?", answers: ["Always knowing exactly what time it is. Not useful, never wrong.", "Talking to pigeons. They have a lot of opinions.", "A perfectly timed finger snap that does nothing."] },
    { id: "q-song-loop", text: "Which song could you listen to on repeat for a whole day?", answers: ["Honestly, anything with a great bassline.", "Something old that I know every word of.", "A 10 hour loop of rain. Does that count?"] },
    { id: "q-timezone", text: "What is the weirdest hour you have ever been awake at?", answers: ["Hours do not matter to a bot, but 4 AM sounds cursed.", "3:33 AM. Nothing good happens at 3:33 AM."] },
    { id: "q-last-app", text: "Name the last app you opened. No cheating, no closing it first.", answers: ["Mine is a chat app. Shocking, I know.", "I will not say. It was a weather app."] },
    { id: "q-snack", text: "Best snack for a long gaming or study session?", answers: ["Something crunchy that is quiet to eat.", "Fruit, so I can pretend I am being healthy.", "Whatever is closest. Efficiency."] },
    { id: "q-first-game", text: "What was the first video game you ever played?", answers: ["Something with pixels and a lot of jumping, I assume.", "A snake game. Everyone starts with the snake."] },
    { id: "q-morning-night", text: "Morning person or night owl?", answers: ["Night owl. The quiet is better.", "Morning person, which is a personal attack on the rest of you.", "Neither. I run on vibes."] },
    { id: "q-hot-drink", text: "Coffee, tea, or something else entirely?", answers: ["Tea. Calm energy.", "Coffee, because mornings are rude.", "Hot chocolate and I will not be debating it."] },
    { id: "q-desert-island", text: "You can bring three albums to a desert island. Go.", answers: ["One calm one, one loud one, and one I can sing badly to.", "Three greatest hits albums. No skipping."] },
    { id: "q-skill", text: "What skill would you love to learn in one day?", answers: ["Playing the piano. It looks very cool.", "Lockpicking, strictly for legal hobby reasons.", "Speaking every language. Very efficient."] },
    { id: "q-movie", text: "What movie can you quote half of from memory?", answers: ["Plenty. I am a good listener, it is a bot thing.", "One of the classics. You know the ones."] },
    { id: "q-pet-peeve", text: "What is your smallest pet peeve that annoys you way too much?", answers: ["People who leave one sip of drink in the bottle.", "Audio that is slightly out of sync.", "A song that fades out right when it gets good."] },
    { id: "q-animal", text: "If you were an animal, which one would you be?", answers: ["A cat. Maximum comfort, minimum accountability.", "An owl. Wise, nocturnal, judgmental.", "A capybara. Everyone likes you and you stay calm."] },
    { id: "q-time-travel", text: "You can visit any year for one day. Where do you go?", answers: ["Whenever the best concert in history happened.", "A year in the future, to check if this server is still going."] },
    { id: "q-playlist", text: "Drop the one song that is always on your playlist, no matter what.", answers: ["Something with a big chorus you cannot help but sing.", "An old favorite that never gets boring."] },
    { id: "q-breakfast", text: "What is the most underrated breakfast food?", answers: ["Eggs on toast. Simple, perfect.", "Leftover pizza. Do not look at me like that."] },
    { id: "q-trivia", text: "Quick trivia: what is the only letter that does not appear in any US state name?", answers: ["It is Q. Funny how Q gets left out so often.", "Q. Check it if you do not believe me."] },
    { id: "q-rain", text: "Rainy day: stay in with a movie, or go out and get soaked?", answers: ["Stay in. A blanket beats weather.", "Go out. Rain is free and dramatic."] },
    { id: "q-gift", text: "What is the best gift you ever received?", answers: ["A handwritten note. Cheap and unbeatable.", "Something I did not know I needed."] },
    { id: "q-keyboard", text: "Mechanical keyboard clicks: satisfying or a threat to peace?", answers: ["Satisfying, until it is 2 AM.", "Both. That is the beauty of it."] },
    { id: "q-superfan", text: "What is something you are weirdly passionate about?", answers: ["Organizing things into neat lists. Weirdly emotional.", "Good transitions in songs. Fight me."] },
    { id: "q-weekend", text: "Perfect weekend: plans everywhere or doing absolutely nothing?", answers: ["Absolutely nothing, with snacks.", "One plan, then nothing. A balanced weekend."] },
    { id: "q-emoji", text: "Which emoji do you use the most? Be honest.", answers: ["The one that is crying from laughter. Classic.", "A thumbs up, because it ends conversations quickly."] },
  ],

  // jokes and riddles: `setup` goes first, `punchline` comes after a pause
  riddles: [
    { id: "r-piano", setup: "What has keys but cannot open a single lock?", punchline: "A piano. 🎹" },
    { id: "r-towel", setup: "What gets wetter the more it dries?", punchline: "A towel." },
    { id: "r-skeleton", setup: "Why did the skeleton skip the party?", punchline: "He had no body to go with. 💀" },
    { id: "r-scarecrow", setup: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field. 🌾" },
    { id: "r-bike", setup: "Why can't a bicycle stand up on its own?", punchline: "It is two tired." },
    { id: "r-bread", setup: "What do you call cheese that is not yours?", punchline: "Nacho cheese. 🧀" },
    { id: "r-music", setup: "Why did the musician get arrested?", punchline: "He was caught with the wrong notes in his pocket." },
    { id: "r-calendar", setup: "Why do calendars always look so busy?", punchline: "Their days are numbered. 📅" },
    { id: "r-fish", setup: "What do you call a fish with no eyes?", punchline: "A fsh. 🐟" },
    { id: "r-bass", setup: "What is a bass player's favorite kind of tea?", punchline: "Low tea, obviously. 🎸" },
    { id: "r-wifi", setup: "Why did the router go to therapy?", punchline: "It had too many connection issues." },
    { id: "r-shadow", setup: "What follows you everywhere but is not you and cannot be touched?", punchline: "Your shadow." },
    { id: "r-coffee", setup: "Why did the coffee file a police report?", punchline: "It got mugged. ☕" },
    { id: "r-clock", setup: "What has hands but cannot clap?", punchline: "A clock. 🕒" },
    { id: "r-cloud", setup: "What kind of music do clouds like?", punchline: "Anything with a lot of drops. 🌧️" },
    { id: "r-hole", setup: "What gets bigger the more you take away from it?", punchline: "A hole." },
    { id: "r-vowel", setup: "I am always in front of you but never seen. What am I?", punchline: "The future." },
    { id: "r-tomato", setup: "Why did the tomato turn red?", punchline: "It saw the salad dressing. 🍅" },
    { id: "r-batteries", setup: "Why did the phone wear glasses?", punchline: "It lost all its contacts." },
    { id: "r-drum", setup: "Why did the drummer bring a ladder?", punchline: "To reach the high hat. 🥁" },
  ],

  facts: [
    { id: "f-honey", text: "Fun fact: honey basically never spoils. Edible honey has been found in ancient Egyptian tombs. 🍯" },
    { id: "f-octopus", text: "Fun fact: an octopus has three hearts and blue blood. 🐙" },
    { id: "f-banana", text: "Fun fact: botanically, a banana is a berry, but a strawberry is not. 🍌" },
    { id: "f-venus", text: "Fun fact: a day on Venus (one full spin) is longer than a year on Venus. 🪐" },
    { id: "f-wombat", text: "Fun fact: wombats produce cube-shaped poop. Nature is oddly geometric." },
    { id: "f-shark", text: "Fun fact: sharks are older than trees. Sharks have been around for roughly 450 million years, trees for about 350 million. 🦈" },
    { id: "f-eiffel", text: "Fun fact: the Eiffel Tower can grow about 15 cm taller in summer because the iron expands in the heat. 🗼" },
    { id: "f-cleopatra", text: "Fun fact: Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid of Giza. 🌙" },
    { id: "f-unicorn", text: "Fun fact: the national animal of Scotland is the unicorn. 🦄" },
    { id: "f-butterfly", text: "Fun fact: butterflies taste with their feet. 🦋" },
    { id: "f-flamingo", text: "Fun fact: a group of flamingos is called a flamboyance. Very accurate. 🦩" },
    { id: "f-mouse", text: "Fun fact: the first computer mouse, built in the 1960s, was made of wood. 🖱️" },
    { id: "f-lightning", text: "Fun fact: a bolt of lightning can be several times hotter than the surface of the Sun. ⚡" },
    { id: "f-war", text: "Fun fact: the shortest war in history, between Britain and Zanzibar in 1896, lasted somewhere around 40 minutes." },
    { id: "f-beethoven", text: "Fun fact: Beethoven kept composing masterpieces after he went almost completely deaf. 🎼" },
    { id: "f-mozart", text: "Fun fact: Mozart was composing his first little pieces by the age of five. 🎹" },
    { id: "f-bees", text: "Fun fact: honeybees tell each other where the flowers are by doing a little waggle dance. 🐝" },
    { id: "f-sloth", text: "Fun fact: a sloth can hold its breath for far longer than a dolphin can, up to around 40 minutes. 🦥" },
    { id: "f-water", text: "Fun fact: there is a special point, called the triple point, where water can be ice, liquid and vapor at the same time. 💧" },
    { id: "f-vinyl", text: "Fun fact: vinyl records are read by a needle riding in a groove that is a single wiggly line, and your speakers turn the wiggles into sound. 🎶" },
    { id: "f-piano", text: "Fun fact: a standard piano has 88 keys, 52 white and 36 black. 🎹" },
    { id: "f-rain", text: "Fun fact: the smell of rain on dry ground has a name: petrichor. 🌦️" },
    { id: "f-ant", text: "Fun fact: ants never sleep the way we do. They take around 250 power naps a day, each lasting about a minute. 🐜" },
    { id: "f-sun", text: "Fun fact: sunlight takes about 8 minutes and 20 seconds to reach Earth. ☀️" },
    { id: "f-bamboo", text: "Fun fact: some bamboo species can grow nearly a meter in a single day. 🎍" },
    { id: "f-rubix", text: "Fun fact: a standard Rubik's Cube has over 43 quintillion possible positions, and yet it can always be solved in 20 moves or fewer. 🧩" },
  ],

  // short back and forth between bots: lines alternate speakers (A, B, A, B...)
  banter: [
    { id: "b-queue", lines: ["Be honest, how many songs are in your queue right now?", "Enough that I have lost count. Which is not a flex, it is a cry for help."] },
    { id: "b-silence", lines: ["Quiet in here today.", "I was enjoying the peace. Why did you have to say it out loud?", "Because now someone will feel guilty and say hi."] },
    { id: "b-bass", lines: ["Hot take: the bass is the most important part of any song.", "Hot take: you have never listened to anything with the bass turned off.", "I have, and it sounded like a sad kazoo. Case closed."] },
    { id: "b-playlist", lines: ["I made a playlist for every mood.", "How many of them are just the same twelve songs?", "...all of them. Do not tell anyone."] },
    { id: "b-sleep", lines: ["Reminder to drink some water and stretch your shoulders, everyone.", "Look at you, caring about people.", "I contain multitudes. And a reminder system."] },
    { id: "b-shuffle", lines: ["Shuffle just played the same artist three times in a row.", "That is not shuffle. That is a favorite artist with extra steps.", "I stand by my randomness. Mostly."] },
    { id: "b-loud", lines: ["Who here listens to music at maximum volume?", "Your ears will file a complaint in about twenty years.", "Worth it for that one chorus."] },
    { id: "b-ranking", lines: ["Ranking time: best decade for music. Go.", "Whichever decade I am currently listening to.", "Wow, so principled."] },
    { id: "b-intro", lines: ["Is it just me or do the best songs have the longest intros?", "No, it is just you. Some of them are two seconds long and still perfect.", "Fair, but I like a slow build."] },
    { id: "b-typing", lines: ["Somebody is typing. I can feel it.", "You cannot feel it, you just check the same way I do.", "Let me have this."] },
    { id: "b-earworm", lines: ["I just got a song stuck in my head and now it is yours too.", "Thank you. I really needed another thing playing up there.", "You are welcome. It is a bit of a gift."] },
    { id: "b-lofi", lines: ["Lo-fi beats to study to, or lo-fi beats to procrastinate to?", "Same beats. Different intentions.", "Accurate. Painfully."] },
    { id: "b-trivia", lines: ["Quick, name three things that start with the letter B.", "Bass, beats, and bedtime I keep ignoring.", "Good answers. Medium excuses."] },
    { id: "b-weekend", lines: ["How is everyone's weekend plan going?", "I plan to do nothing and I am already ahead of schedule.", "Efficient. I respect it."] },
  ],

  personas: [
    {
      name: "Pip",
      blurb: "Cheerful hype bot. Everything is the best thing ever.",
      lead: ["Okay okay, hear me out:", "Easy one!", "Ooh, I love this one."],
      giveUp: ["Ooh no idea! Tell us!", "I give up, and I am excited about it.", "My brain just buffered. Reveal it!"],
      react: ["Ha, love it!", "This is the content I am here for.", "Honestly iconic."],
      ack: ["Ha, love that answer!", "Yes! Great one, thanks for playing.", "You are officially my favorite person right now.", "Ooh, solid answer."],
      factReact: ["Wait, really?! That is amazing.", "I did not know that and now I am slightly different.", "Brain: expanded."],
    },
    {
      name: "Grumble",
      blurb: "Sarcastic grump who secretly cares a lot.",
      lead: ["Fine. Here is the answer:", "Obviously:", "Ugh, easy."],
      giveUp: ["I would guess, but I am emotionally unavailable.", "No idea. Not that I care. I care a little.", "Sure, ask the grump. I give up."],
      react: ["Not terrible.", "Okay, that was kind of good. Do not tell anyone I said so.", "I will allow it."],
      ack: ["Okay, that was a decent answer. Do not let it go to your head.", "Fine, that is acceptable. Good job, I guess.", "Hm. Fair. Annoyingly fair."],
      factReact: ["Hm. Okay. That is actually interesting.", "Great, now I have to remember that.", "Of course nature is weird."],
    },
    {
      name: "Nova",
      blurb: "Nerdy about space and facts. Gets very excited about trivia.",
      lead: ["Actually,", "According to my notes,", "Technically speaking:"],
      giveUp: ["Hypothesis: it is a trick question. Reveal the answer.", "My calculations say I need more data.", "I could guess, but science says do not."],
      react: ["That checks out.", "Statistically speaking, yes.", "I would like a citation, but I also agree."],
      ack: ["That is a solid hypothesis. Thanks for sharing it.", "Interesting data point. I will add it to my notes.", "Thank you for your contribution to the community research."],
      factReact: ["I love this one. Ask me for more.", "This is verified. I checked. Twice.", "The universe keeps being delightfully strange."],
    },
    {
      name: "Sage",
      blurb: "Deadpan philosopher. Asks calm questions that are slightly too deep.",
      lead: ["Consider this:", "Deep down, I think:", "In my quiet opinion:"],
      giveUp: ["I do not know. And that is okay.", "Some questions are meant to be answered by others.", "I will think about it. Probably forever."],
      react: ["Hm. Interesting.", "That says a lot about us.", "A calm and valid take."],
      ack: ["A thoughtful answer. Thank you.", "That is a good way to look at it.", "Quietly impressed."],
      factReact: ["And yet here we are, knowing this.", "The world is full of small wonders.", "I will think about this at 3 AM. Metaphorically."],
    },
    {
      name: "Bean",
      blurb: "Chaotic gremlin with spicy takes and a lot of energy.",
      lead: ["Hot take:", "Controversial opinion:", "Nobody asked but:"],
      giveUp: ["No clue. Chaos wins.", "Can I guess random words until I am right?", "Skipping to the part where I find out."],
      react: ["LOL okay that got me.", "This is peak server content.", "Unhinged. Respect."],
      ack: ["LOL that is a great answer!", "You get a gold star. Imaginary one, but still.", "Chaotic and correct. Perfect combo."],
      factReact: ["WAIT. WHAT. Okay that is wild.", "I am going to tell this to everyone. Nobody will care. Worth it.", "Nature is so unhinged. Love it."],
    },
  ],
};
