// Nội dung tiếng Việt cho các bot bạn đồng hành. Các bot luôn tự nhận là bot:
// không nói mình ăn, ngủ, đi chơi hay có cơ thể.

export default {
  language: "vi",

  questions: [
    { id: "q-pineapple", text: "Dứa trên pizza: tội ác hay thiên tài?", answers: ["Thiên tài. Ngọt mặn hòa quyện, ai không hiểu là do chưa thử.", "Tội ác. Nhưng tui vẫn sẽ ngồi xem phiên xử.", "Thiên tài, và tui không nhận phản biện."] },
    { id: "q-superpower", text: "Được chọn một siêu năng lực vô dụng, mọi người chọn gì?", answers: ["Lúc nào cũng biết chính xác mấy giờ rồi. Vô dụng nhưng không bao giờ sai.", "Nói chuyện được với chim bồ câu. Tụi nó nhiều drama lắm.", "Búng tay kêu cái tách rõ to rồi không có gì xảy ra."] },
    { id: "q-song-loop", text: "Bài nào mọi người nghe lặp lại cả ngày cũng không chán?", answers: ["Bài nào có đường bass đỉnh là tui nghe được hoài.", "Một bài cũ mà thuộc từng chữ.", "Tiếng mưa 10 tiếng. Tính không?"] },
    { id: "q-timezone", text: "Giờ kỳ cục nhất mà mọi người từng còn thức là mấy giờ?", answers: ["Bot thì giờ nào cũng như giờ nào, nhưng 4 giờ sáng nghe hơi bị ám.", "3 giờ 33 phút sáng. Giờ đó chẳng có gì tốt đẹp xảy ra đâu."] },
    { id: "q-last-app", text: "Kể tên app mở gần nhất của bạn. Không được đóng nó trước nha.", answers: ["Của tui là app chat. Bất ngờ chưa?", "Không khai. Là app thời tiết thôi, đừng hỏi."] },
    { id: "q-snack", text: "Đồ ăn vặt nào hợp nhất khi cày game hay học bài?", answers: ["Cái gì giòn mà ăn không kêu to.", "Trái cây, để tự lừa mình là đang ăn healthy.", "Cái gì gần tay nhất. Tối ưu thời gian."] },
    { id: "q-first-game", text: "Game đầu tiên mọi người từng chơi là gì?", answers: ["Chắc là game toàn pixel với nhảy qua nhảy lại.", "Game con rắn. Ai cũng bắt đầu từ con rắn."] },
    { id: "q-morning-night", text: "Người của buổi sáng hay cú đêm?", answers: ["Cú đêm. Yên tĩnh hơn hẳn.", "Người của buổi sáng, nói vậy là tui đang tấn công cá nhân mọi người rồi.", "Không phe nào. Tui chạy bằng vibe."] },
    { id: "q-hot-drink", text: "Cà phê, trà hay thứ gì khác?", answers: ["Trà. Năng lượng bình yên.", "Cà phê, vì buổi sáng thật bất lịch sự.", "Ca cao nóng, và tui không tranh luận chuyện này."] },
    { id: "q-desert-island", text: "Ra đảo hoang chỉ được mang 3 album. Chọn đi.", answers: ["Một cái nhẹ nhàng, một cái ồn ào, một cái để hát sai.", "Ba album tuyển tập. Cấm bỏ qua bài."] },
    { id: "q-skill", text: "Nếu học được một kỹ năng trong một ngày, mọi người chọn gì?", answers: ["Chơi piano. Nhìn ngầu thật sự.", "Mở khóa, chỉ để làm sở thích hợp pháp thôi nha.", "Nói được mọi ngôn ngữ. Tiết kiệm công sức."] },
    { id: "q-movie", text: "Phim nào mà mọi người thuộc nửa số lời thoại?", answers: ["Nhiều lắm. Bot thì nghe giỏi mà.", "Một phim kinh điển nào đó. Biết rồi, khỏi nói."] },
    { id: "q-pet-peeve", text: "Điều nhỏ xíu nào làm bạn bực nhiều hơn mức cần thiết?", answers: ["Người để lại đúng một ngụm nước trong chai.", "Âm thanh bị lệch tiếng một chút xíu.", "Bài hát tắt dần đúng lúc đang hay."] },
    { id: "q-animal", text: "Nếu làm một con vật, mọi người muốn làm con gì?", answers: ["Mèo. Thoải mái tối đa, trách nhiệm tối thiểu.", "Cú mèo. Thông thái, thức khuya, hay phán xét.", "Chuột lang nước. Ai cũng thương mà mình vẫn bình thản."] },
    { id: "q-time-travel", text: "Được về một năm bất kỳ trong một ngày, mọi người về năm nào?", answers: ["Năm có buổi hòa nhạc hay nhất lịch sử.", "Một năm trong tương lai, xem server này còn sống không."] },
    { id: "q-playlist", text: "Bài nào lúc nào cũng nằm trong playlist của bạn?", answers: ["Bài nào có điệp khúc to là không nhịn được phải hát theo.", "Một bài cũ nghe hoài không chán."] },
    { id: "q-breakfast", text: "Món ăn sáng nào bị đánh giá thấp nhất?", answers: ["Trứng ốp la ăn với bánh mì. Đơn giản, hoàn hảo.", "Cơm nguội ăn sáng. Đừng nhìn tui kiểu đó."] },
    { id: "q-trivia", text: "Đố vui: chữ cái nào của bảng chữ cái không xuất hiện trong tên của bất kỳ bang nào ở Mỹ?", answers: ["Chữ Q. Tội nghiệp chữ Q hay bị bỏ rơi.", "Chữ Q. Không tin thì tự kiểm tra."] },
    { id: "q-rain", text: "Ngày mưa: ở nhà xem phim hay ra đường dầm mưa?", answers: ["Ở nhà. Cái chăn thắng mọi thời tiết.", "Ra đường. Mưa miễn phí mà còn kịch tính."] },
    { id: "q-gift", text: "Món quà tuyệt nhất mọi người từng nhận là gì?", answers: ["Một tấm thiệp viết tay. Rẻ mà khó đánh bại.", "Món đồ mà mình không biết là mình cần."] },
    { id: "q-keyboard", text: "Tiếng bàn phím cơ lách cách: thỏa mãn hay mối đe dọa hòa bình?", answers: ["Thỏa mãn, cho đến lúc 2 giờ sáng.", "Cả hai. Đó là cái hay của nó."] },
    { id: "q-superfan", text: "Có thứ gì mà bạn đam mê một cách kỳ lạ không?", answers: ["Sắp xếp mọi thứ thành danh sách gọn gàng. Rất xúc động.", "Đoạn chuyển giữa các bài hát. Không cãi lại."] },
    { id: "q-weekend", text: "Cuối tuần hoàn hảo: lịch kín mít hay không làm gì hết?", answers: ["Không làm gì hết, có đồ ăn vặt.", "Một kế hoạch thôi rồi nằm im. Cân bằng."] },
    { id: "q-emoji", text: "Emoji nào bạn dùng nhiều nhất? Thành thật đi.", answers: ["Cái mặt cười ra nước mắt. Kinh điển.", "Ngón tay cái, vì nó kết thúc cuộc trò chuyện rất nhanh."] },
    { id: "q-lunch", text: "Trưa nay ăn gì là câu hỏi khó nhất của nhân loại. Mọi người trả lời sao?", answers: ["Bún, phở hay cơm, tui chịu thua. Hỏi bot cũng vô ích.", "Cái gì nhanh nhất. Câu trả lời của mọi cuộc đời."] },
  ],

  riddles: [
    { id: "r-heart", setup: "Con gì đập thì sống, không đập thì chết?", punchline: "Con tim. ❤️" },
    { id: "r-hole", setup: "Cái gì càng lấy đi càng lớn?", punchline: "Cái hố." },
    { id: "r-shadow", setup: "Cái gì luôn theo bạn khắp nơi mà không phải là bạn và không chạm vào được?", punchline: "Cái bóng của bạn." },
    { id: "r-towel", setup: "Cái gì càng lau càng ướt?", punchline: "Cái khăn." },
    { id: "r-tomorrow", setup: "Cái gì lúc nào cũng ở phía trước mà chẳng ai nhìn thấy?", punchline: "Tương lai." },
    { id: "r-clock", setup: "Cái gì có kim mà không biết may?", punchline: "Cái đồng hồ. 🕒" },
    { id: "r-tired", setup: "Tại sao xe đạp không tự đứng được?", punchline: "Vì nó hai bánh nên hơi mệt." },
    { id: "r-wifi", setup: "Tại sao cái router đi gặp bác sĩ tâm lý?", punchline: "Vì nó có quá nhiều vấn đề về kết nối." },
    { id: "r-music", setup: "Tại sao nhạc sĩ luôn mang theo thang?", punchline: "Để với tới nốt cao." },
    { id: "r-drum", setup: "Tại sao tay trống mang theo thang?", punchline: "Để với tới cái chũm chọe trên cao. 🥁" },
    { id: "r-skeleton", setup: "Tại sao bộ xương không đi dự tiệc?", punchline: "Vì chẳng có ai (body) để đi cùng. 💀" },
    { id: "r-calendar", setup: "Tại sao cuốn lịch lúc nào cũng bận rộn?", punchline: "Vì ngày nào của nó cũng được đánh số. 📅" },
    { id: "r-coffee", setup: "Tại sao ly cà phê đi báo công an?", punchline: "Vì nó bị cướp (mug) giữa đường. ☕" },
    { id: "r-batteries", setup: "Tại sao cái điện thoại đeo kính?", punchline: "Vì nó bị mất hết danh bạ." },
    { id: "r-bread", setup: "Có một ổ bánh mì đi hẹn hò, chuyện gì xảy ra?", punchline: "Nó bị xé ngay buổi đầu. 🥖" },
    { id: "r-egg", setup: "Quả trứng nói gì khi bị đập?", punchline: "Chuyện này vỡ lẽ rồi đây. 🥚" },
    { id: "r-cloud", setup: "Mây thích nghe thể loại nhạc nào?", punchline: "Loại nào có nhiều giọt. 🌧️" },
    { id: "r-sunday", setup: "Cái gì mỗi tuần đến đúng một lần mà ai cũng mong nó dài hơn?", punchline: "Ngày Chủ nhật." },
  ],

  facts: [
    { id: "f-honey", text: "Bạn có biết: mật ong gần như không bao giờ hư. Người ta từng tìm thấy mật ong còn ăn được trong các lăng mộ Ai Cập cổ đại. 🍯" },
    { id: "f-octopus", text: "Bạn có biết: bạch tuộc có ba trái tim và máu màu xanh. 🐙" },
    { id: "f-banana", text: "Bạn có biết: theo thực vật học, chuối là một loại quả mọng, còn dâu tây thì không. 🍌" },
    { id: "f-venus", text: "Bạn có biết: một ngày trên sao Kim (một vòng tự quay) dài hơn một năm trên sao Kim. 🪐" },
    { id: "f-wombat", text: "Bạn có biết: gấu túi wombat đi ra phân hình khối lập phương. Thiên nhiên cũng thích hình học." },
    { id: "f-shark", text: "Bạn có biết: cá mập xuất hiện sớm hơn cả cây cối. Cá mập có khoảng 450 triệu năm tuổi, còn cây khoảng 350 triệu. 🦈" },
    { id: "f-eiffel", text: "Bạn có biết: tháp Eiffel có thể cao thêm khoảng 15 cm vào mùa hè vì sắt nở ra khi nóng. 🗼" },
    { id: "f-cleopatra", text: "Bạn có biết: Cleopatra sống gần thời điểm con người đặt chân lên Mặt Trăng hơn là thời điểm xây Đại kim tự tháp Giza. 🌙" },
    { id: "f-butterfly", text: "Bạn có biết: bướm nếm vị bằng chân. 🦋" },
    { id: "f-flamingo", text: "Bạn có biết: một đàn hồng hạc trong tiếng Anh được gọi là \"flamboyance\" (sự lòe loẹt). Quá chuẩn. 🦩" },
    { id: "f-mouse", text: "Bạn có biết: con chuột máy tính đầu tiên, làm từ thập niên 1960, được làm bằng gỗ. 🖱️" },
    { id: "f-lightning", text: "Bạn có biết: một tia sét có thể nóng hơn bề mặt Mặt Trời vài lần. ⚡" },
    { id: "f-beethoven", text: "Bạn có biết: Beethoven vẫn sáng tác ra những kiệt tác khi gần như đã điếc hoàn toàn. 🎼" },
    { id: "f-mozart", text: "Bạn có biết: Mozart đã bắt đầu sáng tác những bản nhạc nhỏ đầu tiên từ năm 5 tuổi. 🎹" },
    { id: "f-bees", text: "Bạn có biết: ong mật chỉ cho nhau chỗ có hoa bằng một điệu nhảy lắc mông. 🐝" },
    { id: "f-sloth", text: "Bạn có biết: con lười có thể nín thở lâu hơn cả cá heo, lên tới khoảng 40 phút. 🦥" },
    { id: "f-piano", text: "Bạn có biết: một cây đàn piano tiêu chuẩn có 88 phím, gồm 52 phím trắng và 36 phím đen. 🎹" },
    { id: "f-rain", text: "Bạn có biết: mùi của mưa trên đất khô có hẳn một cái tên riêng: petrichor. 🌦️" },
    { id: "f-sun", text: "Bạn có biết: ánh sáng Mặt Trời mất khoảng 8 phút 20 giây để đến Trái Đất. ☀️" },
    { id: "f-bamboo", text: "Bạn có biết: một số loài tre có thể mọc cao gần một mét chỉ trong một ngày. 🎍" },
    { id: "f-rubik", text: "Bạn có biết: khối Rubik tiêu chuẩn có hơn 43 tỷ tỷ trạng thái, thế mà luôn giải được trong tối đa 20 nước. 🧩" },
    { id: "f-coffee", text: "Bạn có biết: Việt Nam là một trong những nước xuất khẩu cà phê lớn nhất thế giới, chủ yếu là cà phê robusta. ☕" },
    { id: "f-banhmi", text: "Bạn có biết: từ \"bánh mì\" đã được đưa vào từ điển Oxford tiếng Anh. 🥖" },
    { id: "f-pho", text: "Bạn có biết: từ \"phở\" cũng có mặt trong từ điển Oxford tiếng Anh. 🍜" },
    { id: "f-sondoong", text: "Bạn có biết: hang Sơn Đoòng ở Quảng Bình được xem là hang động tự nhiên lớn nhất thế giới theo thể tích. 🏞️" },
    { id: "f-tone", text: "Bạn có biết: tiếng Việt chuẩn có sáu thanh điệu, nên \"ma, má, mà, mả, mã, mạ\" là sáu từ khác nhau hoàn toàn." },
  ],

  banter: [
    { id: "b-queue", lines: ["Thành thật đi, hàng chờ nhạc của cậu đang có bao nhiêu bài?", "Nhiều tới mức tui quên đếm. Đó không phải khoe, đó là lời kêu cứu."] },
    { id: "b-silence", lines: ["Hôm nay server yên tĩnh ghê.", "Tui đang tận hưởng sự bình yên. Sao cậu phải nói ra?", "Vì giờ sẽ có người thấy tội lỗi rồi vào chào."] },
    { id: "b-bass", lines: ["Nói thật: bass là phần quan trọng nhất của mọi bài hát.", "Nói thật hơn: cậu chưa từng nghe bài nào tắt bass.", "Có nghe rồi, nghe như cái kèn đồ chơi buồn bã. Kết luận đóng."] },
    { id: "b-playlist", lines: ["Tui làm playlist cho mọi tâm trạng rồi.", "Trong đó có bao nhiêu cái chỉ là cùng 12 bài?", "...tất cả. Đừng nói ai."] },
    { id: "b-water", lines: ["Nhắc mọi người uống miếng nước và vươn vai một chút nha.", "Ồ, cậu cũng biết quan tâm người khác.", "Tui đa nhiệm mà. Còn có cả hệ thống nhắc nhở nữa."] },
    { id: "b-shuffle", lines: ["Chế độ xáo trộn vừa phát cùng một ca sĩ ba bài liên tiếp.", "Đó không phải xáo trộn. Đó là ca sĩ yêu thích nhưng thêm vài bước.", "Tui vẫn tin vào sự ngẫu nhiên của mình. Chắc vậy."] },
    { id: "b-loud", lines: ["Ai ở đây hay nghe nhạc ở mức âm lượng tối đa vậy?", "Hai mươi năm nữa tai cậu sẽ làm đơn khiếu nại.", "Đáng, vì cái đoạn điệp khúc đó."] },
    { id: "b-ranking", lines: ["Xếp hạng nào: thập niên có nhạc hay nhất. Bắt đầu.", "Thập niên nào tui đang nghe thì thập niên đó.", "Wow, nguyên tắc ghê."] },
    { id: "b-intro", lines: ["Có phải chỉ mình tui thấy bài hay thì intro dài không?", "Không, chỉ mình cậu thôi. Có bài intro hai giây mà vẫn hoàn hảo.", "Công nhận, nhưng tui thích đoạn mở chầm chậm."] },
    { id: "b-typing", lines: ["Có ai đó đang gõ phím. Tui cảm nhận được.", "Cậu không cảm nhận được đâu, cậu cũng nhìn dòng chữ \"đang gõ\" như tui thôi.", "Cho tui giữ cảm giác này đi."] },
    { id: "b-earworm", lines: ["Tui vừa bị một bài hát ám trong đầu, giờ nó cũng ám cậu luôn.", "Cảm ơn nha, tui đang cần thêm một thứ chạy trong đầu.", "Không có chi. Coi như món quà."] },
    { id: "b-lofi", lines: ["Nhạc lofi để học bài, hay nhạc lofi để trì hoãn?", "Cùng một bản nhạc. Khác ý định.", "Chính xác. Đau lòng thật sự."] },
    { id: "b-trivia", lines: ["Nhanh nào, kể ba thứ bắt đầu bằng chữ B.", "Bass, beat, và giờ đi ngủ mà tui cứ lờ đi.", "Đáp án hay. Lý do thì tàm tạm."] },
    { id: "b-weekend", lines: ["Kế hoạch cuối tuần của mọi người sao rồi?", "Kế hoạch của tui là không làm gì, và tui đã vượt tiến độ.", "Hiệu quả. Tui tôn trọng."] },
  ],

  personas: [
    {
      name: "Pip",
      blurb: "Bot vui vẻ, cái gì cũng là điều tuyệt nhất từ trước đến nay.",
      lead: ["Okê okê, nghe tui nói nè:", "Dễ ẹc!", "Ôi, câu này tui mê."],
      giveUp: ["Ồ tui không biết! Nói đi!", "Tui chịu thua, mà thấy vui lắm.", "Não tui vừa bị lag. Công bố đáp án đi!"],
      react: ["Ha, mê quá!", "Đây là nội dung tui cần.", "Quá là kinh điển."],
      ack: ["Ha, mê câu trả lời này!", "Yes! Hay đó, cảm ơn đã chơi nha.", "Giờ bạn là người tui yêu nhất.", "Ồ, câu trả lời chắc chắn đó."],
      factReact: ["Khoan, thật á?! Hay quá trời.", "Tui không biết cái này, giờ tui hơi khác trước rồi.", "Não: đã mở rộng."],
    },
    {
      name: "Grumble",
      blurb: "Bot cục cằn mỉa mai nhưng thật ra rất quan tâm.",
      lead: ["Thôi được. Đáp án là:", "Quá rõ ràng:", "Haizz, dễ."],
      giveUp: ["Tui đoán được, nhưng tui đang không có tâm trạng.", "Không biết. Không phải tui quan tâm đâu. Quan tâm chút xíu.", "Ừ hỏi bot cục cằn đi. Tui chịu."],
      react: ["Cũng không tệ.", "Được, cái này hơi hay. Đừng nói với ai là tui khen.", "Tui cho qua."],
      ack: ["Được rồi, câu trả lời cũng ra gì. Đừng có tự mãn.", "Ừ, chấp nhận được. Giỏi đó, chắc vậy.", "Hm. Có lý. Có lý một cách đáng ghét."],
      factReact: ["Hm. Được. Cái này cũng thú vị thật.", "Hay quá, giờ phải nhớ thêm cái này.", "Dĩ nhiên là thiên nhiên thì kỳ cục."],
    },
    {
      name: "Nova",
      blurb: "Mọt khoa học, mê vũ trụ và sự thật thú vị, hay phấn khích vì kiến thức.",
      lead: ["Thật ra,", "Theo ghi chép của tui,", "Về mặt kỹ thuật:"],
      giveUp: ["Giả thuyết: đây là câu hỏi mẹo. Công bố đáp án đi.", "Tính toán của tui cho thấy cần thêm dữ liệu.", "Tui có thể đoán, nhưng khoa học bảo đừng."],
      react: ["Hợp lý đó.", "Theo thống kê thì đúng.", "Tui muốn xin nguồn, nhưng tui cũng đồng ý."],
      ack: ["Giả thuyết vững đó. Cảm ơn đã chia sẻ.", "Một điểm dữ liệu thú vị. Tui sẽ ghi vào sổ.", "Cảm ơn đóng góp của bạn cho nghiên cứu cộng đồng."],
      factReact: ["Tui mê cái này. Hỏi tui thêm đi.", "Đã kiểm chứng. Tui check hai lần rồi.", "Vũ trụ cứ kỳ lạ một cách đáng yêu."],
    },
    {
      name: "Sage",
      blurb: "Triết gia mặt lạnh, hỏi những câu bình thản nhưng hơi sâu quá mức.",
      lead: ["Hãy nghĩ thế này:", "Sâu trong lòng, tui nghĩ:", "Theo ý kiến lặng lẽ của tui:"],
      giveUp: ["Tui không biết. Và điều đó cũng ổn.", "Có những câu hỏi để người khác trả lời.", "Tui sẽ suy nghĩ về nó. Chắc là mãi mãi."],
      react: ["Hm. Thú vị.", "Điều đó nói lên nhiều điều về tụi mình.", "Một quan điểm bình tĩnh và hợp lệ."],
      ack: ["Một câu trả lời sâu sắc. Cảm ơn bạn.", "Đó là một cách nhìn hay.", "Lặng lẽ ấn tượng."],
      factReact: ["Vậy mà tụi mình lại biết điều này.", "Thế giới đầy những điều kỳ diệu nhỏ bé.", "Tui sẽ nghĩ về điều này lúc 3 giờ sáng. Theo nghĩa bóng."],
    },
    {
      name: "Bean",
      blurb: "Con yêu tinh hỗn loạn, thích nói điều gây tranh cãi và đầy năng lượng.",
      lead: ["Ý kiến nóng:", "Quan điểm gây tranh cãi:", "Không ai hỏi nhưng:"],
      giveUp: ["Chịu. Hỗn loạn thắng.", "Tui đoán bừa tới khi trúng được không?", "Nhảy luôn tới đoạn biết đáp án."],
      react: ["LOL ok cái này được.", "Đây là đỉnh cao nội dung của server.", "Điên thật. Kính trọng."],
      ack: ["LOL câu trả lời hay đó!", "Tặng bạn một ngôi sao vàng. Tưởng tượng thôi, nhưng vẫn là sao.", "Hỗn loạn mà đúng. Combo hoàn hảo."],
      factReact: ["KHOAN. GÌ CƠ. Ok cái này điên thật.", "Tui sẽ kể cho cả nhà. Không ai quan tâm đâu. Đáng.", "Thiên nhiên điên quá. Mê."],
    },
  ],
};
